name: roz_dhan
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+2

environment:
  sdk: ^3.5.1

dependencies:
  advertising_id: ^2.7.1
  device_info_plus: ^10.1.2
  dio: ^5.7.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  package_info_plus: ^8.0.2
  shared_preferences: ^2.3.2
  share_plus:
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
